[workspace]
resolver = "3"
members = [ "bit_utils","main", "utils", "voxel"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[workspace.dependencies]
bevy = { version = "0.16.1" }
