[workspace]
resolver = "3"
members = ["main", "playground", "voxel"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[workspace.dependencies]
bevy = "0.17.0-rc.1"
bevy_flycam = "0.16.1"