[workspace]
resolver = "3"
members = ["main", "math", "playground", "playground_2", "voxel", "wgpu_drawid"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[workspace.dependencies]
bevy = "0.16.1"
bevy_flycam = "0.16.1"
