[workspace]
resolver = "3"
members = ["main", "math", "playground", "voxel"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[workspace.dependencies]
bevy = "0.16.1"
bevy_flycam = "0.16.1"