[package]
name = "main"
version = "0.1.0"
edition = "2024"

[dependencies]
voxel = { path = "../voxel" }
bevy = { workspace = true }
bevy_flycam = "0.16.1"

[features]
dynamic = ["bevy/dynamic_linking"]