[package]
name = "voxel"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bevy = { workspace = true }
block-mesh = "0.2.0"
dashmap = "6.1.0"
ndshape = "0.3.0"
rand = "0.9.2"

[features]
dynamic = ["bevy/dynamic_linking"]
